version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: gagent-cli
    main: ./cmd/gagent-cli
    binary: gagent-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude invalid combinations
    ignore:
      - goos: windows
        goarch: arm64
    # Sign macOS binaries after build
    hooks:
      post:
        - cmd: sh -c 'if [ "{{ .Os }}" = "darwin" ]; then codesign --sign "Developer ID Application" --options runtime --timestamp --verbose "{{ .Path }}"; fi'
          output: true

archives:
  - id: gagent-cli
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - AGENTS.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'

release:
  github:
    owner: ulfschnabel
    name: gagent-cli
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

# Homebrew tap
brews:
  - name: gagent-cli
    repository:
      owner: ulfschnabel
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: https://github.com/ulfschnabel/gagent-cli
    description: "Google Workspace automation CLI for AI agents"
    license: MIT
    install: |
      bin.install "gagent-cli"
    test: |
      system "#{bin}/gagent-cli", "--version"
